CUDA_VISIBLE_DEVICES=0 python main.py --max_epochs=10  --num_workers=8 \
    --model_name_or_path gpt2 \
    --accumulate_grad_batches 4 \
    --batch_size 1 \
    --data_dir dataset/semeval \
    --check_val_every_n_epoch 1 \
    --data_class WIKI80 \
    --max_seq_length 256 \
    --model_class GPTForPrompt \
    --wandb \
    --litmodel_class GPTLitModel2 \
    --task_name wiki80 \
    --lr 3e-6